version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - shared_data:/usr/share/nginx/html

volumes:
  shared_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./src